## 텐서(Tensors)

* 넘파이(NumPy)의 ndarray와 유사

* GPU를 사용한 연산 가속도 가능

In [4]:
import torch

### 파이토치 버전

In [5]:
torch.__version__

'1.9.1+cpu'

### 초기화 되지 않은 행렬

In [6]:
x = torch.empty(4, 2)
x

tensor([[1.0502e-05, 2.1122e+20],
        [3.2870e+21, 3.3382e-09],
        [2.6541e-09, 1.3178e-08],
        [2.1028e+20, 8.4958e+20]])

### 무작위로 초기화된 행렬

In [7]:
x = torch.rand(4, 2)
x

tensor([[0.4316, 0.0751],
        [0.1206, 0.3718],
        [0.0859, 0.5255],
        [0.7955, 0.6552]])

### dtype이 long, 0으로 채워진 텐서

In [8]:
x = torch.zeros(4, 2, dtype = torch.long)
x

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

### 리스트로 텐서만들기

In [9]:
x = torch.tensor([3, 2.3])  
x

tensor([3.0000, 2.3000])

### x를 새롭게 다시 생성

In [13]:
x = x.new_ones(2, 4, dtype = torch.double)  
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

### 평균이 0이고 표준편차가 1인 정규분포를 이용, 사이즈를 기존 텐서를 이용

In [14]:
x = torch.randn_like(x, dtype = torch.float)
x

tensor([[ 0.3824, -0.3313,  0.1610,  0.0839],
        [ 0.3456, -0.4647,  0.3690, -0.5924]])

### 텐서의 크기

In [15]:
x.size()

torch.Size([2, 4])

### 텐서의 연산

In [18]:
x

tensor([[ 0.3824, -0.3313,  0.1610,  0.0839],
        [ 0.3456, -0.4647,  0.3690, -0.5924]])

In [21]:
y = torch.rand(2, 4)
print(y)
print(x + y)
print(torch.add(x, y))

tensor([[0.0394, 0.4903, 0.6340, 0.9102],
        [0.0191, 0.0499, 0.8789, 0.7934]])
tensor([[1.6630, 0.4086, 2.2777, 1.3991],
        [1.2288, 1.1878, 2.2622, 1.7117]])
tensor([[1.6630, 0.4086, 2.2777, 1.3991],
        [1.2288, 1.1878, 2.2622, 1.7117]])


* 결과 텐서를 인자로 제공

In [22]:
result = torch.empty(2, 4)
torch.add(x, y, out = result)

tensor([[1.6630, 0.4086, 2.2777, 1.3991],
        [1.2288, 1.1878, 2.2622, 1.7117]])

* in-place 방식
* 텐서의 값을 변경하는 연산 뒤에는 _가 붙음

In [24]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([[1.6630, 0.4086, 2.2777, 1.3991],
        [1.2288, 1.1878, 2.2622, 1.7117]])
tensor([[0.0394, 0.4903, 0.6340, 0.9102],
        [0.0191, 0.0499, 0.8789, 0.7934]])
tensor([[1.7024, 0.8990, 2.9117, 2.3092],
        [1.2479, 1.2377, 3.1411, 2.5051]])


### 그 외의 연산
* torch.sub : 뺄셈
* torch.mul : 곱셈
* torch.div : 나눗셈
* torch.mm : 내적(dot product)

In [27]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
torch.mm(x, y)

tensor([[0.5786, 0.1503],
        [0.2430, 0.9889]])
tensor([[0.8378, 0.5845],
        [0.5264, 0.9716]])


tensor([[0.5639, 0.4842],
        [0.7242, 1.1029]])

## 텐서의 조작

## 인덱싱
* 넘파이처럼 인덱싱 사용가능

In [28]:
print(x)
print(x[:,1])

tensor([[0.5786, 0.1503],
        [0.2430, 0.9889]])
tensor([0.1503, 0.9889])


## view
* 텐서의 크기(size)나 모양(shape)을 변경

In [29]:
x = torch.randn(4, 5)
y = x.view(20)
z = x.view(5, -1)  # -1은 자동계산

print(x)
print(y)
print(z)

tensor([[-0.4502, -0.3550,  0.8566, -0.4561,  0.1974],
        [ 0.0636,  1.0519,  0.4441,  0.9797,  0.2663],
        [-0.0231, -0.4327,  0.4934, -1.3232, -0.1901],
        [-0.6623, -1.1596,  1.5426, -0.4815, -0.2648]])
tensor([-0.4502, -0.3550,  0.8566, -0.4561,  0.1974,  0.0636,  1.0519,  0.4441,
         0.9797,  0.2663, -0.0231, -0.4327,  0.4934, -1.3232, -0.1901, -0.6623,
        -1.1596,  1.5426, -0.4815, -0.2648])
tensor([[-0.4502, -0.3550,  0.8566, -0.4561],
        [ 0.1974,  0.0636,  1.0519,  0.4441],
        [ 0.9797,  0.2663, -0.0231, -0.4327],
        [ 0.4934, -1.3232, -0.1901, -0.6623],
        [-1.1596,  1.5426, -0.4815, -0.2648]])


### item
* 텐서에 값이 단 하나라도 존재하면 숫자값을 얻을 수 있음

In [30]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.2587])
-0.2586962580680847
torch.float32


* 스칼라값 하나만 존재해야함

In [31]:
x = torch.randn(2)
print(x)
print(x.item())

tensor([-0.4156,  0.3907])


ValueError: only one element tensors can be converted to Python scalars

### squeeze
* 차원을 축소(제거)

In [36]:
tensor = torch.rand(1, 3, 3)
print(tensor)
tensor.shape

tensor([[[0.4005, 0.1993, 0.4667],
         [0.4095, 0.7306, 0.2649],
         [0.3846, 0.6392, 0.2644]]])


torch.Size([1, 3, 3])

In [37]:
t = tensor.squeeze()
print(t)
t.shape

tensor([[0.4005, 0.1993, 0.4667],
        [0.4095, 0.7306, 0.2649],
        [0.3846, 0.6392, 0.2644]])


torch.Size([3, 3])

### unsqueeze
* 차원을 증가(생성)

In [38]:
tensor = torch.rand(1, 3, 3)
print(tensor)
tensor.shape

tensor([[[0.4137, 0.4227, 0.6230],
         [0.5770, 0.2831, 0.5619],
         [0.1631, 0.5152, 0.9009]]])


torch.Size([1, 3, 3])

In [45]:
t = tensor.unsqueeze(dim=0)
print(t)
t.shape

tensor([[[[0.4137, 0.4227, 0.6230],
          [0.5770, 0.2831, 0.5619],
          [0.1631, 0.5152, 0.9009]]]])


torch.Size([1, 1, 3, 3])

### stack
* 텐서간 결합

In [51]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
torch.stack([x, y, z])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

### cat
* 텐서를 결합하는 메소드(concatenate)
* 넘파이의 stack 과 유사하지만 쌓을 dim이 존재해야함
* 예를 들어 해당 차원을 늘려준 후 결함

In [53]:
a = torch.randn(1, 1, 3, 3)
b = torch.randn(1, 1, 3, 3)
c = torch.cat((a, b), dim = 0)

print(c)
print(c.size())

tensor([[[[ 1.6888,  1.4770, -0.9385],
          [ 1.2033, -0.0283,  0.2056],
          [ 0.1625, -0.8324,  0.2591]]],


        [[[-0.2469, -0.7414,  0.7823],
          [ 0.3723, -0.1536,  0.8327],
          [-0.8015,  0.9747,  0.8579]]]])
torch.Size([2, 1, 3, 3])


In [54]:
a = torch.randn(1, 3, 3)
b = torch.randn(1, 3, 3)
c = torch.cat((a, b), dim = 0)

print(c)
print(c.size())

tensor([[[ 0.3725,  0.5246, -0.2202],
         [ 0.1294, -0.7842, -0.2819],
         [-1.6353, -0.2273,  0.5048]],

        [[-0.2093, -0.1785, -0.5688],
         [ 0.8372, -1.9802,  0.5513],
         [-0.1318, -0.2446, -0.1446]]])
torch.Size([2, 3, 3])


### chunk
* 텐서를 여러 개로 나눌 때 사용
* 몇 개의 텐서로 나눌 것이냐

In [55]:
tensor = torch.rand(3, 6)
t1, t2, t3 = torch.chunk(tensor, 3, dim = 1)

print(tensor)
print(t1)
print(t2)
print(t3)

tensor([[0.0560, 0.6273, 0.3707, 0.8737, 0.7144, 0.4247],
        [0.8569, 0.0442, 0.9955, 0.2902, 0.0340, 0.6519],
        [0.3047, 0.9980, 0.9744, 0.2774, 0.1580, 0.6887]])
tensor([[0.0560, 0.6273],
        [0.8569, 0.0442],
        [0.3047, 0.9980]])
tensor([[0.3707, 0.8737],
        [0.9955, 0.2902],
        [0.9744, 0.2774]])
tensor([[0.7144, 0.4247],
        [0.0340, 0.6519],
        [0.1580, 0.6887]])


### split
* chunk와 동일한 기능이지만 조금 다름
* 하나의 텐서당 크기가 얼마이냐

In [56]:
tensor = torch.rand(3, 6)
t1, t2 = torch.split(tensor, 3, dim = 1)

print(tensor)
print(t1)
print(t2)

tensor([[0.8270, 0.7807, 0.2174, 0.6563, 0.8264, 0.7452],
        [0.6929, 0.7896, 0.4738, 0.7316, 0.4245, 0.7533],
        [0.3799, 0.9453, 0.0047, 0.8096, 0.1347, 0.7260]])
tensor([[0.8270, 0.7807, 0.2174],
        [0.6929, 0.7896, 0.4738],
        [0.3799, 0.9453, 0.0047]])
tensor([[0.6563, 0.8264, 0.7452],
        [0.7316, 0.4245, 0.7533],
        [0.8096, 0.1347, 0.7260]])


### torch ↔ numpy
* Torch Tensor(텐서)를 Numpy array(배열)로 변환 가능
* numpy()
* from_numpy()
* Tensor가 CPU상에 있다면 Numpy 배열은 메모리 공간을 공유하므로
  하나가 변하면 다른 하나도 변함

In [57]:
a = torch.ones(7)
a

tensor([1., 1., 1., 1., 1., 1., 1.])

In [58]:
b = a.numpy()
b

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [59]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2. 2.]


In [60]:
import numpy as np
a = np.ones(7)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)
